version: "3"

services:
  robofleet_docker:
    image: robofleet_docker_i
    container_name: robofleet_docker_c
    build:
      # set the build context to the directory containing build files
      context: .
      dockerfile: Dockerfile
    environment:
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
    volumes:
      # mount host directories to the container for persistent storage
      - ../robofleet_client_ws:/root/robofleet_client_ws/
    # give the container access to the host's network
    network_mode: host
    # enable stdin and tty to allow the user to run bash interactively
    stdin_open: true
    tty: true
    # run the entrypoint script
    entrypoint: /entrypoint.sh